# Generated by Django 5.1.1 on 2024-11-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]