# Generated by Django 5.1.1 on 2024-11-08 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOng', '0003_gallery_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery_home',
        ),
    ]
