# Generated by Django 5.1.1 on 2024-11-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOng', '0004_delete_gallery_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
